### ISSUE TITLE
The command argument must be of type string. Received null

### ISSUE THREAD

**Issue by unlucio** [mattduffy/exiftool#9]
I'm not sure why but I cannot seem to be able to use this tool, no matter what I only get 
`/bin/sh: null: command not found` kind of errors.

Here's a little snipped, and its output, that systematically fail for me

Code:
```js
import { Exiftool } from '@mattduffy/exiftool';
let exiftool = await new Exiftool().init('./sample/IMG_7055.jpeg');
let metadata = await exiftool.getMetadata();
console.log(metadata);
```

Result:
```sh
TypeError [ERR_INVALID_ARG_TYPE]: The "command" argument must be of type string. Received null
    at validateString (node:internal/validators:162:11)
    at normalizeExecArgs (node:child_process:190:3)
    at exec (node:child_process:233:16)
    at node:child_process:243:21
    at Exiftool.getMetadata (file:///Users/lucio/code/picturesOrdering/node_modules/@mattduffy/exiftool/src/index.js:905:28)
    at file:///Users/lucio/code/picturesOrdering/src/test.js:3:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE',
  exiftool_command: null
}
```

further info:
```
Error: Command failed: null -config ./node_modules/@mattduffy/exiftool/src/exiftool.config -json -BasicShortcut -groupNames -s3 -quiet --ext cjs --ext css --ext html --ext js --ext json --ext md --ext mjs --ext txt       ./sample/IMG_7055.jpeg
/bin/sh: null: command not found

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:337:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {code: 127, killed: false, signal: null, cmd: 'null -config ./picturesOrderin…cio/code/picturesOrdering/sample/IMG_7055.jpeg', stdout: '', …}
cmd: 'null -config ./node_modules/@mattduffy/exiftool/src/exiftool.config -json -BasicShortcut -groupNames -s3 -quiet --ext cjs --ext css --ext html --ext js --ext json --ext md --ext mjs --ext txt       ./sample/IMG_7055.jpeg'
code: 127
exiftool_command: 'null -config ./node_modules/@mattduffy/exiftool/src/exiftool.config -json -BasicShortcut -groupNames -s3 -quiet --ext cjs --ext css --ext html --ext js --ext json --ext md --ext mjs --ext txt       ./sample/IMG_7055.jpeg'
killed: false
signal: null
stderr: '/bin/sh: null: command not found\n'
stdout: ''
message: 'Command failed: null -config ./node_modules/@mattduffy/exiftool/src/exiftool.config -json -BasicShortcut -groupNames -s3 -quiet --ext cjs --ext css --ext html --ext js --ext json --ext md --ext mjs --ext txt       ./sample/IMG_7055.jpeg\n/bin/sh: null: command not found\n'
stack: 'Error: Command failed: null -config ./node_modules/@mattduffy/exiftool/src/exiftool.config -json -BasicShortcut -groupNames -s3 -quiet --ext cjs --ext css --ext html --ext js --ext json --ext md --ext mjs --ext txt       ./sample/IMG_7055.jpeg\n/bin/sh: null: command not found\n\n    at ChildProcess.exithandler (node:child_process:422:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1105:16)\n    at Socket.<anonymous> (node:internal/child_process:457:11)\n    at Socket.emit (node:events:518:28)\n    at Pipe.<anonymous> (node:net:337:12)\n    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)'
[[Prototype]]: Object
```

PS: Having to create a new obj's instance, init it with a file path, and only then it's possible to get the metadata seems a bit over-engineered if you ask me.

**Comment by mattduffy** [comment]
Hi.  Yes, my library is a node.js package that depends on the presence of the original [Exiftool](https://exiftool.org/) to be installed on the system.  It is very easy to install, with packages for Linux, macOS and Windows.

**Comment by mattduffy** [comment]
> PS: Having to create a new obj's instance, init it with a file path, and only then it's possible to get the metadata seems a bit over-engineered if you ask me.

Just noticed this part.  If you are familiar with creating exiftool queries, you can use the Exiftool.raw(<query>) method.  This method does not rely on any of the setup or option-setting of the demo examples.  It is documented in the Readme.md under the heading **Making Metadata Queries Directly**.  You can issue exiftool queries in one line of code, like this:

```javascript
metadata = await new Exiftool().raw('/usr/local/bin/exiftool -G -s3 -json -b -previewimage -EXIF:GPS* /path/to/my/image.jpg')
```
